services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.8
    container_name: jellyfin
    ports:
      - 8096:8096/tcp
    volumes:
      - /opt/docker/jellyfin/config:/config
      - /opt/docker/jellyfin/cache:/cache
      - /opt/docker/jellyfin/series:/series:ro
      - /opt/docker/jellyfin/movies:/movies:ro
    restart: unless-stopped
    environment:
      JELLYFIN_PublishedServerUrl: ${URL}